change pom; completed the task1; change localization;
RTsolispaick/sem2Java pull request #1
Opened 2024-02-19 18:27 UTC by RTsolispaick

2024-02-28 19:42 UTC, vpyzhyanov requested changes
Решение хорошее, но есть замечания

2024-02-28 19:42 UTC, vpyzhyanov commented on src/main/java/robots/gui/MainApplicationFrame.java
> + * Главное окно прилоежния
очепятка

2024-02-28 19:42 UTC, vpyzhyanov commented on src/main/java/robots/gui/MainApplicationFrame.java
> +    protected void addWindow(JInternalFrame frame) {
обоснуйте почему вы выбрали именно такой уровень видимости

2024-02-28 19:42 UTC, vpyzhyanov commented on src/main/java/robots/gui/PaneMenuBar.java
> +            Logger.debug("Всё очень плохо");
Комментарий не содержательный, совершенно непонятно в чём ошибка. Нужно переписать и добавить сообщение об ошибке из исключения.

2024-02-28 19:42 UTC, vpyzhyanov commented on src/main/java/robots/gui/PaneMenuBar.java
> +    public void setDefaultTheme() {
Обнаружено нарушение ООП. Метод пытается лезть не в своё дело, т.е. в задачу "панели меню" не входит установка темы. Это может делать сами кнопки (действия), но не меню.

Да и метод кажется вообще лишним. Тема по умолчанию есть всегда.

2024-02-29 04:20 UTC, RTsolispaick commented on src/main/java/robots/gui/MainApplicationFrame.java
> +    protected void addWindow(JInternalFrame frame) {
Не подумал об этом, было изначально. Должен быть private, так как методы нужны только для создания объекта MainApplicationFrame.

2024-02-29 04:21 UTC, RTsolispaick commented on src/main/java/robots/gui/PaneMenuBar.java
> +    public void setDefaultTheme() {
Понял, исправлю. Тему менял, потому что не нравилась дефолтная.

2024-02-29 04:35 UTC, RTsolispaick commented
Метод setLookAndFeel перенёс в MainApplicationFrame из PaneMenuBar. Вызов setLookAndFeel в методах PaneMenuBar идёт через обращение к объекту MainApplicationFrame. Изменение темы оставил, потому что она мне также не нравится.

2024-02-29 15:00 UTC, vpyzhyanov commented
хорошо, можете мёрджить

2024-02-29 16:12 UTC, merged