2 task
RTsolispaick/sem2Java pull request #2
Opened 2024-03-18 12:01 UTC by RTsolispaick

2024-03-25 18:30 UTC, vpyzhyanov requested changes
Очень много дублирования. И нет возможности для расширения (в целом можете переписать код потом, но я бы порекомендовал подумать об этом уже сейчас)

2024-03-25 18:30 UTC, vpyzhyanov commented on src/main/java/robots/serialize/Stateful.java
> +    void deformationState(WindowState windowState);
Интересные имена) В переводе на русский "Состояние деформации". Жалко только к методам совершенно не подходят. Ни одного глагола.

Восстановление это resore или load

2024-03-25 18:30 UTC, vpyzhyanov commented on src/main/java/robots/serialize/Stateful.java
> +    WindowState formationState();
сохраненение - это store или save

2024-03-25 18:30 UTC, vpyzhyanov commented on src/main/java/robots/gui/GameWindow.java
> +            setSize(windowState.getWidth(), windowState.getHeight());
получается одни и те же действия будут в каждой компоненте? А если их будет 100? Это не ООП код получается.

2024-03-25 18:30 UTC, vpyzhyanov commented on src/main/java/robots/gui/GameWindow.java
> +            setTitle(windowState.getTitle());
название? Название тоже можно менять? Что-то я не вижу у вас ни одного места, в котором вы добавили изменение названия компоненты

2024-03-25 18:30 UTC, vpyzhyanov commented on src/main/java/robots/gui/GameWindow.java
> +                isIcon());
тоже дублирование

2024-03-25 18:30 UTC, vpyzhyanov commented on src/main/java/robots/gui/LogWindow.java
> +                System.err.println(e.getMessage());
Разве вас не смущает, что реализация deformationState полностью повторяет реализацию в другом компоненте?

2024-03-25 18:30 UTC, vpyzhyanov commented on src/main/java/robots/gui/LogWindow.java
> +                isIcon());
снова полная копия

2024-03-25 18:30 UTC, vpyzhyanov commented on src/main/java/robots/gui/MainApplicationFrame.java
> +            setTitle(windowState.getTitle());
хоть реализация чуть отличается, но тоже много действий повторяется

2024-03-25 18:30 UTC, vpyzhyanov commented on src/main/java/robots/gui/MainApplicationFrame.java
> +                false);
почти дубль

2024-03-25 18:30 UTC, vpyzhyanov commented on src/main/java/robots/serialize/WindowIO.java
> +            System.exit(1);
вы уверены, что отсутствие возможности сохранения должно препятствовать работе программы? Я уверен, что нет)

2024-03-25 18:30 UTC, vpyzhyanov commented on src/main/java/robots/serialize/WindowStateManager.java
> +            System.exit(1);
вы уверены, что отсутствие возможности загрузки состояния должно препятствовать работе программы? Я уверен, что нет)

2024-03-25 18:30 UTC, vpyzhyanov commented on src/main/java/robots/serialize/WindowStateManager.java
> +            ((Stateful) frame).deformationState(windowStateMap.get(frame.getClass().getName()));
можно писать проще:

```java
        if (frame instanceof Stateful stateful)
            stateful.deformationState(windowStateMap.get(frame.getClass().getName()));
```

2024-03-25 18:30 UTC, vpyzhyanov commented on src/main/java/robots/serialize/WindowStateManager.java
> +    public void loadState(JFrame frame, JInternalFrame[] jInternalFrames) {
Используя класс `JInternalFrame` вы заряжаете пистолет и направляете себе в ногу))) Он выстрелит как только появится другой тип окна (в следующей задаче)

2024-03-25 18:30 UTC, vpyzhyanov commented on src/main/java/robots/serialize/WindowStateManager.java
> +    public void saveState(JFrame frame, JInternalFrame[] jInternalFrames) {
аналогично про `JInternalFrame `

2024-03-26 19:18 UTC, RTsolispaick commented
Stateful теперь помечает сериализируемые окна, но не отвечает за их сохранение и восстановление
WindowIO не завершает работу программы, если не получается создать структуру папок; 
WindowStateManager получает извне только Stateful;
WindowState избавились от title по ненадобности;

2024-03-31 18:18 UTC, vpyzhyanov requested changes
Очень хорошо, можете мёрджить. Но посмотрите последние комментарии

2024-03-31 18:18 UTC, vpyzhyanov commented on src/main/java/robots/serialize/WindowStateManager.java
> +                System.err.printf("Нет обработки случая в saveState для %s%n", frame.getClass().getName());
для перевода строки всегда используйте символ `/n`, это стандарт.

2024-03-31 19:52 UTC, merged