Task3
RTsolispaick/sem2Java pull request #3
Opened 2024-04-07 14:06 UTC by RTsolispaick

Изменения:

- Отделены модель игры и её представления.
- Изменена стратегия робота в модели игры.
- Введен класс GameController для координации процесса игры.
- Добавлен класс WindowWithCoordinates с информацией о координатах робота.

2024-04-14 19:06 UTC, vpyzhyanov requested changes
есть замечания

2024-04-14 19:06 UTC, vpyzhyanov commented on src/main/java/robots/controller/GameController.java
> +    public GameVisualizer getGameVisualizer() {
нарушение инкапсуляции. Класс, который представился контроллером, сливает информацию о визуализации. Нехорошо. Да и непонятно зачем, связи с этим классом тут быть не должно

2024-04-14 19:06 UTC, vpyzhyanov commented on src/main/java/robots/controller/GameController.java
> +        robotModel = new RobotModel(propertyChangeSupport);
не понял почему контроллер возомнил себя всемогущим и начал создавать модели, он такой же смертный как и модель и как представление

2024-04-14 19:06 UTC, vpyzhyanov commented on src/main/java/robots/controller/GameController.java
> +        gameVisualizer = new GameVisualizer(propertyChangeSupport);
не понял почему контроллер возомнил себя всемогущим и начал создавать представление, он такой же смертный как и модель и как представление

2024-04-14 19:06 UTC, vpyzhyanov commented on src/main/java/robots/controller/GameController.java
> +        gameVisualizer = new GameVisualizer(propertyChangeSupport);
Акцентирую внимание на то, что связь с представлением исскусственная. Как минимум хранить представление не нужно.

2024-04-14 19:06 UTC, vpyzhyanov commented on src/main/java/robots/gui/GameVisualizer.java
> +    private int targetY;
если эти поля здесь, то чем тогда занимается модель робота? Бездельничает?

2024-04-14 19:06 UTC, vpyzhyanov commented on src/main/java/robots/gui/GameVisualizer.java
> +            updateFields(robotModel.getPosX(),
1. нет нужды "распаковывать" модель, можно просто её передать
2. Не нужно заполнять поля, их в этом классе вообще быть не должно. Эта ответственность принадлежит модели.

2024-04-14 19:06 UTC, vpyzhyanov commented on src/main/java/robots/gui/MainApplicationFrame.java
> +        logWindow.setLocation(10,10);
все эти настройки должны быть в конструторе. А метод можно удалить и просто вызывать конструктор

2024-04-14 19:06 UTC, vpyzhyanov commented on src/main/java/robots/gui/MainApplicationFrame.java
> +        gameWindow.setBounds(230, 10,
аналогично

2024-04-14 19:06 UTC, vpyzhyanov commented on src/main/java/robots/gui/MainApplicationFrame.java
> +        windowWithCoordinates.setLocation(770, 10);
аналогично

2024-04-14 19:06 UTC, vpyzhyanov commented on src/main/java/robots/models/RobotModel.java
> +    public synchronized void update() {
Вы уверены, что этот метод нужно делать синхронизированным? С какой целью вы это сделали?

Вы явно своей цели не добились, зато приложение может существенно подтормаживать. Лучше уберите пока, подучите многопоточность, а потом ещё раз подумайте нужна ли синхронизация в этом случае

2024-04-15 18:43 UTC, vpyzhyanov commented on src/main/java/robots/models/RobotModel.java
> +    public synchronized void update() {
Не вижу ответов на вопросы!

2024-04-15 18:54 UTC, RTsolispaick commented on src/main/java/robots/controller/GameController.java
> +    public GameVisualizer getGameVisualizer() {
Согласен, визуализация теперь создаётся в GameWindow. GameControler теперь принимает RobotModel и GameVisualizer для организации взаимодействия пользователя с моделью через графический интерфейс.

2024-04-15 18:57 UTC, RTsolispaick commented on src/main/java/robots/controller/GameController.java
> +        robotModel = new RobotModel(propertyChangeSupport);
Исправлено. GameControler не создаёт ни модель, ни представление. Он принимает их в качестве параметров в конструкторе и сохраняет модель в качестве поля класса GameController для использования в методе start.

2024-04-15 18:57 UTC, RTsolispaick commented on src/main/java/robots/controller/GameController.java
> +        gameVisualizer = new GameVisualizer(propertyChangeSupport);
Ответил выше.

2024-04-15 19:02 UTC, RTsolispaick commented on src/main/java/robots/gui/GameVisualizer.java
> +    private int targetY;
Модель робота генерирует эти данные. Они хранились в GameVisualizer, как необходимые для отрисовки. Это один из вариантов. Можно также хранить модель робота для того, чтобы не дублировать данные и извлекать их из неё уже в процессе перерисовки.

2024-04-15 19:09 UTC, RTsolispaick commented on src/main/java/robots/gui/GameVisualizer.java
> +            updateFields(robotModel.getPosX(),
Поскольку мы не можем добавлять параметры в переопределяемые методы, такие как paintComponent, мы не можем передать модель напрямую в этот метод. Единственный вариант, который мне приходит в голову для уменьшения количества полей в классе, - это хранить модель в качестве поля класса GameVisualizer.

2024-04-15 19:10 UTC, RTsolispaick commented on src/main/java/robots/gui/MainApplicationFrame.java
> +        logWindow.setLocation(10,10);
Перенесено в конструктор и удалены все методы с cозданием окон

2024-04-15 19:19 UTC, RTsolispaick commented on src/main/java/robots/models/RobotModel.java
> +    public synchronized void update() {
Во время рефакторинга, когда код был другим, возникали проблемы с тем, что каким то невообразимым образом у меня появлялись странные данные в момент пересчёта угла поворота. Почему то тогда я подумал, что это слово тут к месту, уже не помню почему я так подумал. Тогда код был другой и я не могу вспомнить, что так конкретно было. В тот момент, возможно мне повезло, перестали возникать странные значения и я оставил его. Сейчас я вижу, что в нём нет необходимости.

2024-04-15 19:43 UTC, vpyzhyanov commented on src/main/java/robots/models/RobotModel.java
> +    public synchronized void update() {
метод тыка значит.... хорошая штука, но если головой работать, то лучше результат будет

2024-04-15 19:43 UTC, vpyzhyanov commented on src/main/java/robots/gui/GameVisualizer.java
> +    private int targetY;
не можно, а нужно

2024-04-15 19:44 UTC, vpyzhyanov commented
Хорошо, можете мёрджить

2024-04-16 08:47 UTC, merged