task4
RTsolispaick/sem2Java pull request #4
Opened 2024-04-28 19:08 UTC by RTsolispaick

Для обеспечения потокобезопасности и предотвращения утечек памяти в источнике сообщений лога были внесены следующие изменения:
- Создана потокобезопасная структура данных CircularBuffer для хранения записей лога. При записи в буфер блокируется доступ к объекту, гарантируя целостность данных.
- При чтении диапазона данных возвращается потокобезопасный итератор. Потокобезопасность обеспечивается путем сохранения необходимых данных внутри итератора. Это позволяет избежать одновременного доступа к буферу из разных потоков.
- Список слушателей теперь хранит слабые ссылки на объекты. Слабые ссылки не препятствуют сборщику мусора удалять объекты, когда на них больше нет сильных ссылок. Это предотвращает утечки памяти, которые могут возникать, когда слушатели лога больше не нужны.

2024-04-29 19:14 UTC, vpyzhyanov requested changes
есть замечания

2024-04-29 19:14 UTC, vpyzhyanov commented on src/main/java/robots/log/CircularBuffer.java
> +                snapshot[i] = buffer[(head + start + i) % capacity];
1. потокобезопасность куда-то растворилась. При получении итератора нет никакой синхронизации
2. (уже не так критично) Ну и копирование это довольно затраты, вроде довольно быстро, но всё равно затраты

2024-04-29 19:14 UTC, vpyzhyanov commented on src/main/java/robots/log/CircularBuffer.java
> +            remainingElements--;
не занимайте память и процессор под лишние поля. Это поле просто инвертирует `currentPosition`. Так что можно спокойно выкинуть и заменить через `currentPosition` и `length`

2024-04-29 19:14 UTC, vpyzhyanov commented on src/main/java/robots/log/LogWindowSource.java
> +                    activeListeners = temp.toArray(new LogChangeListener [0]);
ну дела.... взяли и перечеркнули все свои старания и избавлению от утечек памяти.... очень жаль....а могли ведь использовать слабые ссылки и в этом случае тоже.

Если начали дело, то идите до конца, не сдавайтесь, иначе всё может быть напрасно)

2024-04-29 20:53 UTC, RTsolispaick commented on src/main/java/robots/log/CircularBuffer.java
> +                snapshot[i] = buffer[(head + start + i) % capacity];
Итератор теперь не делает снимок буфера. Всё сделано просто через synchronized.

2024-04-29 20:54 UTC, RTsolispaick commented on src/main/java/robots/log/CircularBuffer.java
> +            remainingElements--;
Исправлено

2024-04-29 20:55 UTC, RTsolispaick commented on src/main/java/robots/log/LogWindowSource.java
> +                    activeListeners = temp.toArray(new LogChangeListener [0]);
m_activeListeners теперь тоже хранит слабые ссылки на LogChangeListener.

2024-04-30 16:10 UTC, vpyzhyanov commented on src/main/java/robots/log/CircularBuffer.java
> +                snapshot[i] = buffer[(head + start + i) % capacity];
Стало намного хуже, чем было.

1. Не исправлено вообще никак! Как думаете почему? (что такое synchronized мы на паре уже обсудили, вы должны уже это знать)
2. Уж лучше бы просто оставили копирование. Тот способ, что вы выбрали плох тем, что пока кто-то читает итератор данные могут измениться, а итератор выведет уже другие данные (т.е. будет разрушен)

2024-04-30 16:11 UTC, vpyzhyanov commented on src/main/java/robots/log/LogWindowSource.java
> +                    activeListeners = temp.toArray(new LogChangeListener [0]);
теперь комментарий не соответствует действительности)

2024-04-30 16:14 UTC, vpyzhyanov requested changes
Проблема не исправлена

2024-04-30 18:25 UTC, RTsolispaick commented on src/main/java/robots/log/CircularBuffer.java
> +                snapshot[i] = buffer[(head + start + i) % capacity];
Ответ на первое. Просто блокируется доступ к объекту итератора из других потоков при использовании его методов, но не обеспечиваем безопасный доступ к данным. 
Я не смог придумать, как защитить итератор от изменения данных в буфере, кроме как изначальный мой вариант с снимком буфера. Поэтому я вернулся к прошлому варианту, но на этот раз при обращении к буферу я использую synchronized.

2024-04-30 18:28 UTC, RTsolispaick commented on src/main/java/robots/log/LogWindowSource.java
> +                    activeListeners = temp.toArray(new LogChangeListener [0]);
Я осознал, что m_activeListeners нужен для кэширования слушателей и избегания повторной синхронизации массива слушателей. Поэтому вернул m_activeListeners, только теперь это ArrayList<WeakReference<LogChangeListener>>.

2024-04-30 18:36 UTC, vpyzhyanov commented on src/main/java/robots/log/CircularBuffer.java
> +                snapshot[i] = buffer[(head + start + i) % capacity];
Неправильный ответ. В этом варианте вообще ничего не блокируется. Почему?

> Я не смог придумать, как защитить итератор от изменения данных в буфере, кроме как изначальный мой вариант с снимком буфера. Поэтому я вернулся к прошлому варианту, но на этот раз при обращении к буферу я использую synchronized.

Норм вариант. Он хотя бы решает проблему.

2024-04-30 18:39 UTC, vpyzhyanov approved these changes
Хорошо, можете мёрджить

2024-05-06 07:45 UTC, merged