task5
RTsolispaick/sem2Java pull request #5
Opened 2024-05-12 22:24 UTC by RTsolispaick

Изменения:
- Реализована локализация приложения. Для этого использовался класс ResourceBundle. Класс LanguageManager предоставляет доступ к единственному экземпляру класса ResourceBundle. Хоть это и не было нужно, но реализовано сохранение языка пользователя при помощи класса LocaleIO. При смене языка пересоздаётся главное окно со всеми его внутренними окнами.
- Для сообщения лога создан отдельный паттерн. Для того, чтобы не пересоздавать объект MessageFormat для одного и того же паттерна добавлен класс MessageFormatCache, который предоставляет объекты MessageFormat по паттерну, если они есть в кеше. Если для паттерна не найдётся объекта MessageFormat, то этот объект создаётся и сохраняется в кеше.

2024-05-13 20:26 UTC, vpyzhyanov requested changes
есть замечания

2024-05-13 20:26 UTC, vpyzhyanov commented on src/main/java/robots/gui/GameWindow.java
> +        super(LanguageManager.getBundle().getString("game.title"),
для имён свойств лучше выбирать имена согласованные с их местами использования. Так их будет удобнее найти и быстрее понять к какому классу они относятся. Например "GameWindow.title", т.к. в классе GameWindow определяется поле title

2024-05-13 20:26 UTC, vpyzhyanov commented on src/main/java/robots/gui/GameWindow.java
> +        String[] title = {LanguageManager.getBundle().getString("game.title")};
зачем вам массив из одного элемента? Кажется это лишнее

2024-05-13 20:26 UTC, vpyzhyanov commented on src/main/java/robots/gui/GameWindow.java
> +                        LanguageManager.getBundle().getString("logger.pattern")
Раз уж вы делаете статику, то делайте её удобной и не используйте посредников `LanguageManager.getString("logger.pattern")`

2024-05-13 20:26 UTC, vpyzhyanov commented on src/main/java/robots/locale/LanguageManager.java
> +    private static volatile ResourceBundle instanceBundle;
О нет, изменяемое статическое поле. Помянем ООП и принципы SOLID ((((

Зачем volatile? Если вы меняете её в интерфейсе, то там всего один поток

2024-05-13 20:26 UTC, vpyzhyanov commented on src/main/java/robots/locale/LanguageManager.java
> +    public synchronized static boolean setLocale(Locale locale) {
1. Статика - зло. Она сыграет с вами злую шутку при неправильном использовании
2. Синхронная статика - ищадие ада. При неаккуратном использовании она способна снизить производительность приложения до нуля.

2024-05-13 20:26 UTC, vpyzhyanov commented on src/main/java/robots/locale/LanguageManager.java
> +        localeIO.saveLocaleToJson(locale);
"сохранить локаль в JSON". А JSON куда засунуть? Этого в названии не сказано. JSON - это просто формат, это не конечная цель.

2024-05-13 20:26 UTC, vpyzhyanov commented on src/main/java/robots/locale/MessageFormatCache.java
> +    private static final Map<String, MessageFormat> messageFormatCache = new ConcurrentHashMap<>();
1. статика - зло. Уберите её.
2. я бы не блокировал доступ к кешу, это чревато сильной деградацией производительности. Как минимум на чтение точно блокировать не стоит.

2024-05-13 20:26 UTC, vpyzhyanov commented on src/main/java/robots/serialize/LocaleIO.java
> + * Класс для сериализации и десериализации локали в JSON файл.
> JSON файл

Такого файла не существует. JSON - это просто формат.

2024-05-13 20:26 UTC, vpyzhyanov commented on src/main/java/robots/serialize/LocaleIO.java
> +            System.err.println("Не удалось создать структуру приложения");
Вы никогда не узнаете почему не удалось. А всё потому, что не вывели ни стек, ни сообщение об исходной ошибке. Нужно и то, и другое.

2024-05-13 20:26 UTC, vpyzhyanov commented on src/main/java/robots/serialize/LocaleIO.java
> +            System.err.println("Ошибка в OutputStream");
аналогично

2024-05-13 20:26 UTC, vpyzhyanov commented on src/main/java/robots/serialize/LocaleIO.java
> +            System.err.println("Файл не существует" + e.getMessage());
хоть что-то. Но стек тоже был бы очень полезен при разборе ошибок

2024-05-13 20:26 UTC, vpyzhyanov commented on src/main/resources/locale_ru.properties
> +bar.lang.en=Английский
языки лучше всегда писать на своём же языке. Это уже стало стандартом. Тут надо English.

2024-05-13 20:26 UTC, vpyzhyanov commented on src/main/java/robots/gui/MainApplicationFrame.java
> +    public void closeWindowForRestart() {
где JavaDoc?

2024-05-13 20:26 UTC, vpyzhyanov commented on src/main/java/robots/locale/LanguageManager.java
> +public class LanguageManager {
правильнее использовать синглтон

2024-05-14 14:20 UTC, RTsolispaick commented on src/main/java/robots/gui/GameWindow.java
> +        super(LanguageManager.getBundle().getString("game.title"),
Имена свойств изменены

2024-05-14 14:24 UTC, RTsolispaick commented on src/main/java/robots/gui/GameWindow.java
> +        String[] title = {LanguageManager.getBundle().getString("game.title")};
Как я понял MessageFormat принимает только массив объектов, поэтому приходится оборачивать в массив.

2024-05-14 14:24 UTC, RTsolispaick commented on src/main/java/robots/gui/GameWindow.java
> +                        LanguageManager.getBundle().getString("logger.pattern")
Исправлено

2024-05-14 14:25 UTC, RTsolispaick commented on src/main/java/robots/locale/LanguageManager.java
> +    private static volatile ResourceBundle instanceBundle;
LanguageManager теперь синглтон, который хранит в приватном поле ResourceBundle.

2024-05-14 14:33 UTC, RTsolispaick commented on src/main/java/robots/locale/LanguageManager.java
> +    public synchronized static boolean setLocale(Locale locale) {
Синхронизации большен нет, так как мы изменяем локаль только в интерфейсе в одном потоке. Также потоки обращаются к ResourceBundle только на чтение и после изменения локали происходит пересоздание главного окна. Поэтому конфликтных ситуаций, требующих синхронизации, не возникает.

2024-05-14 14:33 UTC, RTsolispaick commented on src/main/java/robots/locale/LanguageManager.java
> +        localeIO.saveLocaleToJson(locale);
Метод переименован в saveLocaleToFile

2024-05-14 14:37 UTC, RTsolispaick commented on src/main/java/robots/locale/MessageFormatCache.java
> +    private static final Map<String, MessageFormat> messageFormatCache = new ConcurrentHashMap<>();
MessageFormatCache теперь синглтон. Также потокобезопасная структура данных заменена на обычный HashMap. Если будут возникать конфликтные ситуации, то больше, чем к малым потерям по производительности (из-за одновременного создания несколько не находящихся в кеше объектов MessageFormer) это не приведёт.

2024-05-14 14:38 UTC, RTsolispaick commented on src/main/java/robots/serialize/LocaleIO.java
> + * Класс для сериализации и десериализации локали в JSON файл.
Исправлено

2024-05-14 14:39 UTC, RTsolispaick commented on src/main/java/robots/serialize/LocaleIO.java
> +            System.err.println("Не удалось создать структуру приложения");
Добавлено сообщение об исходной ошибки и выводится стек вызовов.

2024-05-14 14:39 UTC, RTsolispaick commented on src/main/java/robots/serialize/LocaleIO.java
> +            System.err.println("Ошибка в OutputStream");
Аналогично исправлено

2024-05-14 14:39 UTC, RTsolispaick commented on src/main/java/robots/serialize/LocaleIO.java
> +            System.err.println("Файл не существует" + e.getMessage());
Добавлен вывод стека вызовов

2024-05-14 14:39 UTC, RTsolispaick commented on src/main/resources/locale_ru.properties
> +bar.lang.en=Английский
Исправлено

2024-05-14 14:41 UTC, RTsolispaick commented on src/main/java/robots/gui/MainApplicationFrame.java
> +    public void closeWindowForRestart() {
Метод удалил. Теперь просто в переопределённом dispose у MainApplicationFrame вызывается saveStatesWindows для сохранения состояния окон перед освобождением ресурсов.

2024-05-14 14:42 UTC, RTsolispaick commented on src/main/java/robots/locale/LanguageManager.java
> +public class LanguageManager {
Написал выше по поводу этого.

2024-05-14 18:20 UTC, vpyzhyanov commented on src/main/java/robots/gui/GameWindow.java
> +        String[] title = {LanguageManager.getBundle().getString("game.title")};
А могли бы сделать удобный метод в вашем классе `MessageFormatCache` и передавать произвольное количество аргументов с помощью `...`

2024-05-14 18:49 UTC, vpyzhyanov requested changes
Хорошо. Как исправите, последние замечания можете мёрджить.

2024-05-14 18:49 UTC, vpyzhyanov commented on src/main/java/robots/serialize/LocaleIO.java
> +            System.err.println("Не удалось создать структуру приложения");
Правильнее делать это за одну запись: `System.err.println("Не удалось создать структуру приложения. Причина: " + e.getMessage());`

Другие потоки тоже могут писать в лог(консоль) сообщения, поэтому между ними может быть разрыв. Даже может оказаться так, что одна часть вашего сообщения на одной странице, а другая на другой.

2024-05-14 18:49 UTC, vpyzhyanov commented on src/main/java/robots/serialize/LocaleIO.java
> +            System.err.println(e.getMessage());
аналогично. Не надо разрывать одно сообщение

2024-05-14 20:16 UTC, merged